# Docs: https://github.com/Azure/webapps-deploy
# https://github.com/Azure/actions

name: Build and deploy fullstack Metlink Tracker

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Set up Node.js (for React)
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install React dependencies
        working-directory: ./metlink-frontend
        run: npm install

      - name: Build React app
        working-directory: ./metlink-frontend
        run: npm run build

      - name: Publish ASP.NET Core app
        run: dotnet publish MetlinkTransitAPI/MetlinkTransitAPI.csproj -c Release -o publish_output

      - name: Copy React build contents into published wwwroot
        run: |
          if (!(Test-Path "publish_output/wwwroot")) {
            New-Item -ItemType Directory -Force -Path "publish_output/wwwroot" | Out-Null
          }
          Copy-Item -Recurse -Force "metlink-frontend/build/" "publish_output/wwwroot"

      - name: List final wwwroot contents (debug)
        run: Get-ChildItem -Recurse -Path "publish_output/wwwroot"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: fullstack-app
          path: publish_output

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: fullstack-app
          path: fullstack-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'metlink-tracker'
          slot-name: 'Production'
          package: fullstack-app
