# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy fullstack Metlink Tracker

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Set up Node.js (for React)
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install React dependencies
        working-directory: ./metlink-frontend
        run: npm install

      - name: Build React app
        working-directory: ./metlink-frontend
        run: npm run build

      - name: Copy React build to ASP.NET Core wwwroot
        run: |
          if (Test-Path "MetlinkTransitAPI\wwwroot") {
            Remove-Item -Recurse -Force "MetlinkTransitAPI\wwwroot"
          }
          Copy-Item -Recurse -Force "metlink-frontend\build" "MetlinkTransitAPI\wwwroot"


      - name: Publish ASP.NET Core app
        run: dotnet publish MetlinkTransitAPI/MetlinkTransitAPI.csproj -c Release -o publish_output

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: fullstack-app
          path: publish_output

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: fullstack-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'metlink-tracker'
          slot-name: 'Production'
          package: .
